#I __SOURCE_DIRECTORY__
#r "packages/Akka/lib/net45/Akka.dll"
#r "packages/Akka.FSharp/lib/net45/Akka.FSharp.dll"
#r "packages/FsPickler/lib/net45/FsPickler.dll"
#r "packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll"
#r "packages/Akka.Persistence/lib/net45/Akka.Persistence.dll"
#r "packages/Akka.Persistence.FSharp/lib/net45/Akka.Persistence.FSharp.dll"
#r "packages/Google.ProtocolBuffers/lib/net40/Google.ProtocolBuffers.dll"
#r "packages/Google.ProtocolBuffers/lib/net40/Google.ProtocolBuffers.Serialization.dll"